[project]
name = "cs4453"
version = "0.1.0"
description = "cs4453 project"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch",
    "numpy<2.0",
    "gymnasium",
    "minigrid",
    "matplotlib",
    "matplotlib-inline<0.2",
    "rliable",
    "wandb",
    "rllte-core",
    "scipy",
    "jupyter",
    "arch>=7.1,<7.2",
    "pandas<3",
]
